const actionTypes = {
  LOAD_CART_REQUEST: 'LOAD_CART_REQUEST',
  LOAD_CART_SUCCESS: 'LOAD_CART_SUCCESS',
  LOAD_CART_FAIL: 'LOAD_CART_FAIL',

  LOAD_CART_SERVICES_REQUEST: 'LOAD_CART_SERVICES_REQUEST',
  LOAD_CART_SERVICES_SUCCESS: 'LOAD_CART_SERVICES_SUCCESS',
  LOAD_CART_SERVICES_FAIL: 'LOAD_CART_SERVICES_FAIL',

  LOAD_SERVICES_SLOTS_REQUEST: 'LOAD_SERVICES_SLOTS_REQUEST',
  LOAD_SERVICES_SLOTS_SUCCESS: 'LOAD_SERVICES_SLOTS_SUCCESS',
  LOAD_SERVICES_SLOTS_FAIL: 'LOAD_SERVICES_SLOTS_FAIL',

  LOAD_STUDIO_SERVICES_REQUEST: 'LOAD_STUDIO_SERVICES_REQUEST',
  LOAD_STUDIO_SERVICES_SUCCESS: 'LOAD_STUDIO_SERVICES_SUCCESS',
  LOAD_STUDIO_SERVICES_FAIL: 'LOAD_STUDIO_SERVICES_FAIL',

  LOAD_HOME_REQUEST: 'LOAD_HOME_REQUEST',
  LOAD_HOME_SUCCESS: 'LOAD_HOME_SUCCESS',
  LOAD_HOME_FAIL: 'LOAD_HOME_FAIL',

  ADD_SLOTS_REQUEST: 'ADD_SLOTS_REQUEST',
  ADD_SLOTS_SUCCESS: 'ADD_SLOTS_SUCCESS',
  ADD_SLOTS_FAIL: 'ADD_SLOTS_FAIL',
};

export default actionTypes;
