const actionTypes = {
  LOAD_HOME_REQUEST: 'LOAD_HOME_REQUEST',
  LOAD_HOME_SUCCESS: 'LOAD_HOME_SUCCESS',
  LOAD_HOME_FAIL: 'LOAD_HOME_FAIL',

  ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
  ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
  ADD_TO_CART_FAIL: 'ADD_TO_CART_FAIL',
};

export default actionTypes;
